<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<AnalysisMode>None</AnalysisMode>
		<UseWindowsForms>True</UseWindowsForms>
		<ImplicitUsings>Enable</ImplicitUsings>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		<OutputPath>bin</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <WarningLevel>1</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <WarningLevel>1</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AssimpNet" Version="4.1.0" />
		<PackageReference Include="MonoGame.Forms.DX" Version="3.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Pfim" Version="0.11.4" />
	  	<Reference Include="SoulsFormats" HintPath="SoulsFormats.dll" />
	  	<None Update="SoulsFormats.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
	  	<None Include="Logo.ico" Visible="false" />
	  	<None Include="Icon.ico" Visible="false" />
		<None Remove="README.md" />
		<None Remove="Screenshot.png" />
	</ItemGroup>

	<Target Name="PostBuildCleanup" AfterTargets="Build">
		<Exec Command="rd /s /q bin\runtimes" />
  	</Target>
</Project>